version: 2
jobs:
  build:
    docker:
      - image: node:8.4.0
    working_directory: ~/app
    environment:
      DOCKER_REPO: stefanwalther/verb
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - add_ssh_keys
      - setup_remote_docker:
          version: 17.07.0-ce
      - run:
          name: Install Docker client
          command: ./scripts/cci2-install-docker-client.sh "17.07.0-ce" "edge"
      - run:
          name: Update version tag
          command: |
            set -e
            VER=$(node -e "console.log(require('./package.json').version)")

            # If a git tag is not set or if the tag does not match release pattern e.g. v1.2.3, then add the cci build number to the version.
            RELEASE_PATTERN="v[0-9].*"
            if [[ -z "${CIRCLE_TAG}" || ! $CIRCLE_TAG =~ $RELEASE_PATTERN ]]; then
              VER+="-$CIRCLE_BUILD_NUM"
              npm version $VER --no-git-tag-version
            fi
            echo "$VER" > ./version.txt
      - run:
          name: Build Docker image
          command: |
            VER=$(cat ./version.txt)
            docker build -t $DOCKER_REPO:$VER .
#      - run:
#          name: Test
#          command: |
#            cd test
#            ./test.sh
      - run:
          name: Login to Docker
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      - deploy:
          name: Push image to Docker Hub
          command: |
            # Only branch "master" is being pushed to Docker Hub
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              VER=$(cat ./version.txt)
              docker tag $DOCKER_REPO:$VER $DOCKER_REPO:latest
            fi
            docker push $DOCKER_REPO
      # test: https://github.com/moby/moby/issues/21280

