name: Docker Image CI
on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master]


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      # Build :tag only if there is a tag
      - name: Build the tagged Docker image
        if: startsWith(github.ref, 'refs/tags/v')
        run: docker build . --file Dockerfile --tag stefanwalther/verb:${{steps.vars.outputs.tag}}

      - name: Push the tagged Docker image
        if: startsWith(github.ref, 'refs/tags/v')
        run: docker push stefanwalther/verb:${{steps.vars.outputs.tag}}

      # Build :latest all the time
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag stefanwalther/verb:latest

      - name: Push the latest Docker image
        run: docker push stefanwalther/verb:latest
